### PR TITLE
fixing icon path

### PR DESCRIPTION
**Pull request by BryanSchuetz**
#97 

Changes path to the icon.

### CODE REVIEW

**Comment by chriscoyier** [comment]
Is this ultimately supposed to the icon for the built application? 

Screen Shot 2020-07-30 at 8 38 47 PM

After I build, I get the default Electron icon still. Maybe I have to do something special?

**Comment by BryanSchuetz** [comment]
For MacOS I think it needs to be an .icns file. For windows it probably needs to be an .ico file. For Linux maybe the .png just works? I think you just include each as a flag when packaging for each platform: `icon=build/icons/icon.icns`

I can take a stab at making the .ico/.icns files.

**Comment by ondreian** [comment]
I tried to find the `.svg` i made originally, but I can't seem to find it anywhere. :frowning_face:

**Comment by chriscoyier** [comment]
Any thoughts on getting a new fancy one designed?

I kinda run in some design circles and I would definitely enjoy commissioning an app icon for this project.

**Comment by ondreian** [comment]
i'm not beholden to the current one, I just want it to have some sort of tie in to game lore around the [illthorn tree](https://gswiki.play.net/Illthorn) if possible.

**Comment by chriscoyier** [comment]
That's awesome. For sure. 

Anything else that you think of that is kind of part of the soul of the project that you'd love to see reflected in the icon lemme know. It's already a great name and there is lots to draw from with it.

**Comment by chriscoyier** [comment]
> I tried to find the .svg i made originally, but I can't seem to find it anywhere. ☹️

I wonder if it was this? https://d.pr/f/fVM9AN

I think that was my bad for removing, I didn't see it referenced anywhere.

**Comment by ondreian** [comment]
No problem, generally dead code pruning is great, and it's moot if we are going to get a fancy one made. :slightly_smiling_face:

**Comment by chriscoyier** [comment]
should be fix in new icons merge

**Pull request closed without merging**
