### PR TITLE
fix: upgrade electron to fix build on arm64

### PR DESCRIPTION
**Pull request by hovatterz**
Building/packaging now works on arm64

Tested on a 2020 M1 Macbook Pro

---

It's several major version jumps, so I'm not expecting a fast merge or anything. If anyone finds this helpful that's great :). I'll be maintaining a fork that builds for macOS for the foreseeable future.

### CODE REVIEW

**Comment by ondreian** [comment]
I have tried bumping the version a few times, and am very open to it, but for some reason the newer versions supported less ES5 syntax-isms, maybe this one fixes that.

**Comment by ondreian** [comment]
I spun it up just to quickly smoke test it for stuff that we don't have unit tests for currently, and it seems like the feed "stickiness" is broken, so that will need to be fixed up before it is merged.  Otherwise, the whole host of syntax errors does not seem to exist.

**Comment by hovatterz** [comment]
@ondreian I'll see if I can recreate and fix that today. Can you shoot over some instructions on how to create the problem?

**Comment by ondreian** [comment]
if you start a session and connect to it, the main feed doesn't scroll down as lines come in was how I saw it. I'm on Ubuntu, so it might be that newer electron is calculating something slightly different in my environment

**Pull request closed without merging**
