### PR TITLE
updating readme with current installation and customization instructions

### PR DESCRIPTION
**Pull request by BryanSchuetz**
I've never really worked with Electron before and it took me a minute to figure out how to run/build/customize things...so I added some instructions to the README for others.

### CODE REVIEW

**Comment by BryanSchuetz** [comment]
will do

**Comment by ondreian** [comment]
I forgot to mention pruning the already committed `.DS_store` file, from before the addition to `.gitignore, from the current branch so it doesn't make it to `master`

**Comment by BryanSchuetz** [comment]
Sorry, should probably have been able to figure that out. 😀 Afraid I'm a bit fumbly when it comes to submitting pull requests...but hopefully will get better.

**Comment by ondreian** [comment]
Thanks for your contribution :tada:

**Pull request merged**
